pipeline {
    agent any
    stages { 
        stage('Clone') {
            steps{
                echo 'Clone pipeline 1 - production'
            }
            
        }
        stage('Build') {
           steps{
                echo 'Clone pipeline 1 - production'
            }
        }
        stage('Test') {
           steps{
                echo 'Clone pipeline 1 - production'
            }
        }
        stage('Deploy') {
            steps{
                echo 'Clone pipeline 1 - production'
            }
        }
    }
}