pipeline {
    agent any
    triggers {
        GenericTrigger(
            genericHeaderVariables: [
                [key: 'X-GitHub-Event', regexpFilter: '']
            ],
            genericVariables: [
                [key: 'ref', value: '$.pull_request.base.ref', expressionType: 'JSONPath', regexpFilter: '', defaultValue: ''],
                [key: 'action', value: '$.action', expressionType: 'JSONPath', regexpFilter: '', defaultValue: '']
            ],
            // causeString: 'Triggered on $ref',
            regexpFilterText: '${x_github_event}&&${ref}',
            regexpFilterExpression: 'push&&refs/heads/main',
            token: 'RO3bV0fpMs',
            printContributedVariables: true,
            printPostContent: true,
        )
    }
    environment {
        AWS_ACCESS_KEY_ID = "${credentials('devops-main').accessKeyId}"
        AWS_SECRET_ACCESS_KEY = "${credentials('devops-main').secretKey}"
    }
    stages {
        stage('Pipeline 1: GIT Checkout SCM') {
            steps {
                checkout([$class: 'GitSCM',
                  branches: [[name: ref]],
                  userRemoteConfigs: [[url: 'https://github.com/minhquoc1299/dc11-dot-quoctran-w4-terraform.git',
                                      credentialsId: 'github-account']]])
            }
        }

        stage('Pipeline 2: Terraform Apply') {
            steps {
                script {
                    sh 'terraform workspace select main'
                    sh 'terraform init -no-color'
                    sh 'terraform apply -auto-approve -no-color'
                }
            }
        }
    }

    post {
        failure {
            mail(
                bcc: '',
                body: "Dear Manager,\n\nTerraform deploy failed. Please check the build logs for details.\n\nThanks,\nJenkins System",
                cc: 'tmquoc@tma.com.vn',
                from: '',
                replyTo: '',
                subject: '[PR] Terraform PR Build Fail',
                to: 'manager@yopmail.com'
            )
        }
    }
}
